Repository 737genie/Quiz, pull requests merged in 2025-09, with the labels that each got.

#10 9월 22일 문제 resources 추가
  Quiz_0922/src/main/resources/static/css/component.css
  Quiz_0922/src/main/resources/static/css/style.css
  Quiz_0922/src/main/resources/static/js/cart.js
  Quiz_0922/src/main/resources/static/js/memory-treasures.js
  Quiz_0922/src/main/resources/static/js/products.js
  Quiz_0922/src/main/resources/static/js/simulator.js
  Quiz_0922/src/main/resources/templates/admin-dashboard.html
  Quiz_0922/src/main/resources/templates/cart.html
  Quiz_0922/src/main/resources/templates/index.html
  Quiz_0922/src/main/resources/templates/login.html
  Quiz_0922/src/main/resources/templates/memory-siumulator.html
  Quiz_0922/src/main/resources/templates/order.html
  Quiz_0922/src/main/resources/templates/product-detail.html
  Quiz_0922/src/main/resources/templates/products.html
  Quiz_0922/src/main/resources/templates/signup.html
  Quiz_0922/src/main/resources/templates/user-profile.html
Labels: feat, frontend

#15 Feature/pjh
  Quiz_0922/src/main/java/com/example/demo/security/Securityconfig.java
Labels: feat, backend

#18 9월 22일 문제 패키지 추가
  Quiz_0922/src/main/java/com/example/demo/branchTest.java
  Quiz_0922/src/main/java/com/example/demo/controller/AdminController.java
  Quiz_0922/src/main/java/com/example/demo/global/Securityconfig.java
  Quiz_0922/src/main/java/com/example/demo/haha/hhhh.java
  Quiz_0922/src/main/java/com/example/demo/jihodevtest.java
  Quiz_0922/src/main/java/com/example/demo/login/loginController.java
  Quiz_0922/src/main/java/com/example/demo/login/loginRepostiory.java
  Quiz_0922/src/main/java/com/example/demo/login/loginService.java
  Quiz_0922/src/main/java/com/example/demo/test.java
Labels: feat, backend

#20 gradle-setting
  Quiz_0922/build.gradle
Labels: chore, backend

#21 [0925] 유저 기능 구현 및 index.html 경로 수정
  Quiz_0922/src/main/java/com/example/demo/user/SiteUsers.java
  Quiz_0922/src/main/java/com/example/demo/user/UserCharacter.java
  Quiz_0922/src/main/java/com/example/demo/user/UserController.java
  Quiz_0922/src/main/java/com/example/demo/user/UserDto.java
  Quiz_0922/src/main/java/com/example/demo/user/UserRepository.java
  Quiz_0922/src/main/java/com/example/demo/user/UserService.java
  Quiz_0922/src/main/resources/templates/index.html
Labels: feat, backend, frontend

#22 시큐리티 작업
  Quiz_0922/build.gradle
  Quiz_0922/src/main/java/com/example/demo/global/Securityconfig.java
  Quiz_0922/src/main/java/com/example/demo/global/UserRole.java
Labels: chore, backend

#23 [0925] Order 기능 구현 및 html 경로 수정
  Quiz_0922/src/main/java/com/example/demo/order/CalculateRequestDto.java
  Quiz_0922/src/main/java/com/example/demo/order/OrderAPIController.java
  Quiz_0922/src/main/java/com/example/demo/order/OrderController.java
  Quiz_0922/src/main/java/com/example/demo/order/OrderDTO.java
  Quiz_0922/src/main/java/com/example/demo/order/OrderRepository.java
  Quiz_0922/src/main/java/com/example/demo/order/OrderService.java
  Quiz_0922/src/main/java/com/example/demo/order/OrderSummaryDTO.java
  Quiz_0922/src/main/java/com/example/demo/order/Orders.java
  Quiz_0922/src/main/resources/templates/order.html
Labels: feat, backend, frontend

#29 250926
  Quiz_0922/.gitignore
  Quiz_0922/src/main/java/com/example/demo/cart/AddToCartRequest.java
  Quiz_0922/src/main/java/com/example/demo/cart/Cart.java
  Quiz_0922/src/main/java/com/example/demo/cart/CartApiController.java
  Quiz_0922/src/main/java/com/example/demo/cart/CartController.java
  Quiz_0922/src/main/java/com/example/demo/cart/CartItem.java
  Quiz_0922/src/main/java/com/example/demo/cart/CartItemDto.java
  Quiz_0922/src/main/java/com/example/demo/cart/CartItemRepository.java
  Quiz_0922/src/main/java/com/example/demo/cart/CartService.java
  Quiz_0922/src/main/java/com/example/demo/cart/CartSummaryDto.java
Labels: feat, 도와주세요..., backend
